name: Mi workflow

on: push

jobs:
  tareas:
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write
      
    steps:
      - name: Escaneo de codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
